defaults:
  - model: "bert_base"
  - args: "default_args"
  - _self_


hydra:
  sweeper:
    params:
      model: glob(*)
      args.dataset_name: /home/gpucce/Repos/abstraction_ladders/acl_abstraction_ladders/abstraction_ladders_resources/src/primary_school/training_datasets/training_data_all_no_spec.ds,/home/gpucce/Repos/abstraction_ladders/acl_abstraction_ladders/abstraction_ladders_resources/src/primary_school/training_datasets/training_t1_test_t2_no_spec.ds,/home/gpucce/Repos/abstraction_ladders/acl_abstraction_ladders/abstraction_ladders_resources/src/primary_school/training_datasets/training_t2_test_t1_no_spec.ds,/home/gpucce/Repos/abstraction_ladders/acl_abstraction_ladders/abstraction_ladders_resources/src/primary_school/training_datasets/training_data_all_with_spec.ds,/home/gpucce/Repos/abstraction_ladders/acl_abstraction_ladders/abstraction_ladders_resources/src/primary_school/training_datasets/training_t1_test_t2_with_spec.ds,/home/gpucce/Repos/abstraction_ladders/acl_abstraction_ladders/abstraction_ladders_resources/src/primary_school/training_datasets/training_t2_test_t1_with_spec.ds
