dataset_name: /home/gpucce/Repos/abstraction_ladders/acl_abstraction_ladders/abstraction_ladders_resources/src/primary_school_data/training_datasets/training_data_all_no_spec.ds
max_length: 128
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
learning_rate: 5e-5
num_train_epochs: 3
seed: 42
output_dir: "."
num_warmup_steps: 0
pad_to_max_length: false
weight_decay: 0.0
checkpointing_steps: "epoch"
gradient_accumulation_steps: 1
return_entity_level_metrics: true
resume_from_checkpoint: false
experiment_name: "ner_experiment"
with_tracking: true
report_to: "wandb"